#!/bin/bash

# Python2
#PYTHON="python2"
: ${PYTHON2:?"ERROR: env var PYTHON2 is undefined"}

# Convert NLM .nxml to text and standoff annotations

set -u
set -e

USAGESTR="Usage: $0 NXMLFILE [TEXTFILE] [SOFILE]"
SRC="nxml2txt/src"

if [ $# -lt 1 -o $# -gt 3 ]; then
    echo $USAGESTR
    exit 1
fi

nxmlfn=$1

if [ ! -f $nxmlfn ]; then
    echo "$nxmlfn: No such file"
    exit 1
fi

if [ $# -gt 1 ]; then
    textfn=$2
else
    textfn=${nxmlfn%.nxml}.txt
fi

if [ $# -gt 2 ]; then
    sofn=$3
else
    sofn=${nxmlfn%.nxml}.so
fi

#cat $nxmlfn |
    #$PYTHON2 $SRC/rewritetex.py - -s -v |
    #$PYTHON2 $SRC/rewritemmla.py - -s -v |
    #$PYTHON2 $SRC/respace.py - -s |
    #$PYTHON2 $SRC/rewriteu2a.py - -s |
    #$PYTHON2 $SRC/standoff.py - $textfn $sofn

cat $nxmlfn |
    $PYTHON2 $SRC/respace.py - -s |
    $PYTHON2 $SRC/rewriteu2a.py - -s |
    $PYTHON2 $SRC/standoff.py - $textfn $sofn
        
